import { Paytone_One, Outfit } from "next/font/google";
import Navbar from "@/components/ui/layout/Navbar";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const paytone = Paytone_One({
  subsets: ["latin"],
  variable: "--font-paytone",
  display: "swap",
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${paytone.variable} ${outfit.variable}`}>
      <body>
        <div id="contact-modal"></div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
